#ifndef WIDGET_RENDERER_HELPER_H
#define WIDGET_RENDERER_HELPER_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <stdint.h>
#include <assert.h>
#include <stddef.h>
#include <string.h>
#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>

#include <vulkan/vulkan.h>
#include "vk_mem_alloc.h"
#include <math.h>

#ifndef NK_NUKLEAR_H_
#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_DEFAULT_FONT
#include "nuklear.h"
#endif

#ifndef NK_GLFW_TEXT_MAX
#define NK_GLFW_TEXT_MAX 256
#endif

#ifndef NK_GLFW_DOUBLE_CLICK_LO
#define NK_GLFW_DOUBLE_CLICK_LO 0.02
#endif

#ifndef NK_GLFW_DOUBLE_CLICK_HI
#define NK_GLFW_DOUBLE_CLICK_HI 0.2
#endif

#ifndef NK_GLFW_MAX_TEXTURES
#define NK_GLFW_MAX_TEXTURES 256
#endif


enum nk_glfw_init_state { NK_GLFW3_DEFAULT = 0, NK_GLFW3_INSTALL_CALLBACKS };


struct Mat4f
{
    float m[16];
};

#define VK_COLOR_COMPONENT_MASK_RGBA                                           \
    VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |                      \
        VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT

struct nk_glfw_vertex
{
    float position[2];
    float uv[2];
    nk_byte col[4];
};


/*
 * Handle used by the engine/application to refer to a renderer.
 */
typedef Handle WidgetRendererHandle;
/*
 * Data uploaded to the widget uniform buffer.
 */
struct WidgetUniform
{
    mat4 ortho;
};
/*
 * Vertex layout expected by the Nuklear Vulkan pipeline.
 */

/*
 * Small internal replacement types used by the GLFW/Nuklear input code.
 */
struct wr_vec2
{
    float x;
    float y;
};

typedef int8_t wr_char;

struct NkVertex
{
    float pos[2];
    float uv[2];
    nk_byte color[4];
};
/*
 * Vulkan resources belonging to one frame-in-flight.
 */
typedef struct WidgetFrameData
{
/// NEW VARS
// Memory Pointers and Buffers
    VkBuffer uniform_buffer;
    VkDeviceMemory uniform_memory;
    void *mapped_uniform;

    VkBuffer vertex_buffer;
    VkDeviceMemory vertex_memory;
    void *mapped_vertex;

    VkBuffer index_buffer;
    VkDeviceMemory index_memory;
    void *mapped_index;

    VkDescriptorSet uniform_descriptor_set;    

// Buffer Storage sizes and uniform fixed size
    uint32_t max_vertex_buffer;		// maximum vertexes by count this memory vertex_buffer can hold
    uint32_t max_index_buffer;		// maximum indexes by count this memory index_buffer can hold
    uint32_t uniform_buffer_size;	// maximum sizeof this memory uniform_buffer can hold

    /*
     * Number of indices generated by nk_convert() for this frame.
     */
    uint32_t index_count;
    
    // GUI width to compare to swapchain extent for drawing
    uint32_t width;
    uint32_t height;
}WidgetFrameData;

typedef struct nk_vulkan_texture_descriptor_set 
{
    VkImageView     image_view;
    VkDescriptorSet descriptor_set;
} NkVulkanTextureDescriptorSet;

typedef struct WidgetRenderer
{
    /*
     * Window and input integration.
     */
    GLFWwindow *window;

    int width;
    int height;
    int display_width;
    int display_height;

    bool callbacks_installed;

    /*
     * Optional previous GLFW callbacks.
     *
     * Needed only if the renderer must restore callbacks installed
     * by another subsystem when it shuts down.
     */
    GLFWscrollfun       previous_scroll_callback;
    GLFWcharfun         previous_char_callback;
    GLFWkeyfun          previous_key_callback;
    GLFWmousebuttonfun  previous_mouse_button_callback;

    /*
     * Nuklear context and command state.
     */
    struct nk_context          ctx;
    struct nk_font_atlas       atlas;
    struct nk_buffer           cmds;
    struct nk_draw_null_texture tex_null;
    nk_handle font_tex;

    /*
     * Input state.
     */
    struct wr_vec2 fb_scale;
    struct wr_vec2 scroll;

    unsigned int text[NK_GLFW_TEXT_MAX];
    wr_char key_events[NK_KEY_MAX];
    int text_len;

    double last_button_click;
    int is_double_click_down;

    struct wr_vec2 double_click_pos;
    float delta_time_seconds_last;

    /*
     * Persistent application widget state.
     */
    int demo_operation;
    int compression;

    struct nk_colorf background;
    struct nk_image image;

    /*
     * Vulkan pipeline state.
     */
    VkPipeline       pipeline;
    VkPipelineLayout pipeline_layout;

    VkDescriptorSetLayout uniform_descriptor_set_layout;
    VkDescriptorSetLayout texture_descriptor_set_layout;

    /*
     * Registered texture descriptors.
     */
    NkVulkanTextureDescriptorSet *texture_descriptor_sets;
    uint32_t texture_descriptor_sets_len;
    uint32_t texture_descriptor_sets_capacity;

    /*
     * Font resources.
     */
    
    //// NEW VARS
    VkImage       font_image;
    VkDeviceMemory font_memory;
    VkImageView   font_image_view;
    VkDescriptorSet font_descriptor_set;    
    

    /*
     * Per-frame Vulkan resources.
     */
    struct WidgetFrameData frame[VK_FRAMES];

    uint32_t quad_count;

    struct WidgetVertex *quad_vertices;
    size_t quad_vertex_capacity;
    
    VkBuffer      vertex_gpu_buffer;
    VmaAllocation vertex_gpu_alloc;

    VkBuffer      index_gpu_buffer;
    VmaAllocation index_gpu_alloc;    
    
    struct nk_buffer vertex_nk_buffer;
    struct nk_buffer index_nk_buffer;    
    
    
    struct nk_allocator nk_allocator;
    bool nk_initialized;
    struct nk_convert_config convert_config;
    // old nk_glfw state for callbacks and others.
    enum nk_glfw_init_state init_state;
    
}WidgetRenderer;

/*
 * Internal widget-renderer helpers.
 *
 * These are not required in the public widget_renderer.h header.
 */
void
WidgetInstallFonts(void);

bool
WidgetRendererRecord(WidgetRenderer *renderer,
                     VkEngine *engine,
                     VkFrame *vk_frame,
                     WidgetFrameData *ui_frame);
    

/*
 * Initialize the Nuklear context and input backend.
 */

/*
 * Destroy Nuklear context, font atlas, buffers, and input backend.
 */
void
WidgetRendererDestroy(WidgetRendererHandle handle);

/*
 * Update GLFW input and begin a new Nuklear frame.
 */
void
WidgetRendererBuildWidgets();


/*
 * Build the WidgetRenderer UI.
 */
WidgetRendererHandle
WidgetRendererInit(struct VkEngine *vk);

/*
 * Convert Nuklear draw commands and upload them to Vulkan buffers.
 */
bool WidgetRendererUpdate(struct Frame *frame);


/*
 * Record Nuklear Vulkan draw commands into an active render pass.
 */
void
widget_renderer_draw();
/*
 * Reset transient renderer state.
 */

#define NK_API extern
NK_API void nk_glfw3_char_callback(GLFWwindow *win, unsigned int codepoint);
NK_API void nk_glfw3_key_callback(GLFWwindow *win, int key, int scancode, int action, int mods);
NK_API void nk_glfw3_scroll_callback(GLFWwindow *win, double xoff, double yoff);
NK_API void nk_glfw3_mouse_button_callback(GLFWwindow *win, int button, int action, int mods);


#endif /* WIDGET_RENDERER_HELPER_H */
