#ifndef SRC_ENGINE_RES_RES_H
#define SRC_ENGINE_RES_RES_H

#include "common.h"

enum Resource {
	RES_NONE,
	RES_TEAPOT,
	RES_TEXTURE_TEST,
	RES_SHADER_FRAG_TEST,
	RES_SHADER_VERT_TEST,
	RES_SHADER_FRAG_TEXT,
	RES_SHADER_VERT_TEXT,
	RES_SHADER_FRAG_WIDGET,
	RES_SHADER_VERT_WIDGET,

	RES_SHADER_FRAG_SOFTBODY,
	RES_SHADER_VERT_SOFTBODY,
	RES_SHADER_VERT_SOFTBODY_SHADOW,

	RES_SHADER_FRAG_WIREFRAME,
	RES_SHADER_VERT_WIREFRAME,

	RES_SHADER_FRAG_SPHERE,
	RES_SHADER_VERT_SPHERE,
	RES_SHADER_VERT_VOXEL,
	RES_SHADER_FRAG_VOXEL,
	
	RES_SHADER_SHADOW_VERT_VOXEL,
	RES_SHADER_SHADOW_FRAG_VOXEL,
	
	RES_NUKLEAR_FRAG_GUI,
	RES_NUKLEAR_VERT_GUI
	
};

void *res_file(enum Resource, size_t *);

#endif /* SRC_ENGINE_RES_RES_H */
